{
  "apiVersion": "sparkoperator.k8s.io/v1beta2",
  "kind": "SparkApplication",
  "metadata": { "name": "appkantariapd", "namespace": "ccma-pre" },
  "spec":
    {
      "type": "Java",
      "sparkUIOptions": { "serviceType": "NodePort" },
      "timeToLiveSeconds": 600,
      "mode": "cluster",
      "sparkConf":
        {
          "spark.eventLog.enabled": "true",
          "spark.eventLog.dir": "s3a://spark/logs/",
          "spark.history.fs.logDirectory": "s3a://spark/logs/",
          "spark.history.fs.update.interval": "5s",
          "spark.hadoop.fs.s3a.access.key": "ZZ0JLR12PPW4410IW3G9",
          "spark.hadoop.fs.s3a.secret.key": "***",
          "spark.hadoop.fs.s3a.endpoint": "10.210.4.193:8080",
          "spark.hadoop.fs.s3a.port": "8080",
          "spark.hadoop.fs.defaultFS": "s3a://ccma-pre",
          "spark.hadoop.fs.s3a.path.style.access": "true",
          "spark.hadoop.fs.s3a.connection.ssl.enabled": "false",
          "spark.executor.extraJavaOptions": "-Dcom.amazonaws.services.s3.enableV4=true",
          "spark.driver.extraJavaOptions": "-Dcom.amazonaws.services.s3.enableV4=true",
          "spark.hadoop.fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem",
          "spark.hive.metastore.uris": "thrift://metastore.ccma-pre.svc.cluster.local:9850",
          "spark.hive.metastore.warehouse.dir": "s3a://ccma-pre",
        },
      "image": "fps99/sparkr-s3:v6.8",
      "imagePullPolicy": "IfNotPresent",
      "mainClass": "com.pragsis.ccma.etl.control.ControlProcess",
      "mainApplicationFile": "s3a://ccma-pre/enterprise/zapping/etl/ccma-etl-0.2314.4-jar-with-dependencies.jar",
      "sparkVersion": "3.1",
      "arguments": ["kantar_iapd"],
      "restartPolicy": { "type": "Never" },
      "driver":
        {
          "cores": 2,
          "memory": "6144m",
          "serviceAccount": "spark-operator",
          "configMaps":
            [
              { "name": "hive-site-cm", "path": "/opt/spark/conf" },
              { "name": "core-site-cm", "path": "/opt/spark/conf" },
            ],
        },
      "executor":
        {
          "cores": 1,
          "instances": 1,
          "memory": "2049m",
          "configMaps":
            [
              { "name": "hive-site-cm", "path": "/opt/spark/conf" },
              { "name": "core-site-cm", "path": "/opt/spark/conf" },
            ],
        },
    },
}
